version: '3.8'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock_visualizer_flask
    container_name: flask_stock
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"
      FLASK_APP: app.py